#ifndef MENU_ITEM_H
#define MENU_ITEM_H

#include <stdint.h>
#include "clock_ui.h"

/*
 * this is the header-file for the autogenerated menu_items.c file which
 * is generated by the generate-menu.py script. It contains two lists of items,
 * one for the menu structure, and one for the "chooser" items which are used
 * to choose from one of several items in a lite.
 */

/* menu contexts, will be the value of arg2 when action == CLOCK_UI_MENU */
#define MENU_CONTEXT_CHANNEL 1

struct menu_item {
	const char *name; /* point to name of this item in PROGMEM */
	uint8_t next_id; /* next item index in menu_items */
	uint8_t prev_id; /* prev item index in menu_items */

	/* which clock_ui screen to show upon selection, arg1..3 depend on this */
	enum clock_ui_state action;
	uint8_t arg1;
	uint8_t arg2;
	uint8_t arg3;

	/* action == CLOCK_UI_MENU
	     arg1: submenu index to go to
	     arg2: which "context" to store when entering this menu, e.g. CONTEXT_CHANNEL
	     arg3: value of the "context"

	   action == CLOCK_UI_CHOOSE
	     arg1: index into chooser_items list, which selection of items to use
	     arg2: which type of chooser_items (one of enum chooser_item_type)
	*/
};

enum chooser_item_type {
	CHOOSER_ITEM_OUTPUT_MODE,
	CHOOSER_ITEM_OUTPUT_POLARITY,
	CHOOSER_ITEM_INPUT_POLARITY,
	CHOOSER_ITEM_TIMER_DIRECTION,
};

struct chooser_item {
	const char *name; /* point to name of this item in PROGMEM */
	uint8_t next_id; /* item index of following item */
	uint8_t prev_id; /* item index of preceding item */
	uint8_t value; /* value to set the corresponding "type" to */
};

extern const PROGMEM struct menu_item menu_items[];
extern const PROGMEM struct chooser_item chooser_items[];

#endif